### ISSUE TITLE
Text message low balance notification options

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea-dash#67]
This used to have options for email, but now it's text:

![image](https://user-images.githubusercontent.com/1335122/53982100-0a3bf980-40e2-11e9-936a-5a3c361eab1f.png)

**Comment by jkilpatr** [comment]
well it works with email as well it should check the exit auth method.

**Comment by jtremback** [comment]
Also I don't know why Yalda used that weird X checkbox, just use a standard bootstrap checkbox element.

**Comment by asoltys** [comment]
So this setting only gets applied to the currently selected exit? In that case would we hide or disable this form if an exit hasn't been selected yet? What happens if the user changes exits? 

Also, do we really want to capture a phone number again here rather than use the one they registered with? Does that imply that they can enter a different number or email than the one they used to sign up with?

One solution might be to have a single checkbox to turn notifications on or off that works regardless of the auth method and gets communicated to whatever exit they connect to. The text could read something like "When low balance notifications are enabled you will receive a text or email alert from your exit server when your account is running low depending on which registration method was used."

**Comment by jtremback** [comment]
Yea, sorry this would be intended to change the phone number. When the user sees it, it will already have their number in it.

**Comment by jtremback** [comment]
We should have a conversation to spec the technical and UX elements of this out more.
